### ISSUE TITLE
client/Producer: Close() is not flushing current inflight messages

### ISSUE THREAD

**Issue by brenol** [rabbitmq/rabbitmq-stream-go-client#103]
Hi, found a issue with the library using (*Producer).Close() while messages are still inflight. It does not seem to be flushing them.

Using (*Environment).Close() works, though.

Thanks!

**Comment by Gsantomaggio** [comment]
Hi @brenol ,
Thank you for reporting. We will have a look!

**Comment by brenol** [comment]
@Gsantomaggio sorry, I forgot to add sample code. Here it is: https://play.golang.org/p/LwmFjXMEslO

Sample output, using env.Close():
```shell
$ go run main.go
2021/11/08 14:50:54 produced 67303 messages
2021/11/08 14:50:55 got close notification. Produced: 67303, Consumed: 67303
```

Using prod.Close():
```shell
go run main.go
2021/11/08 14:51:17 produced 65994 messages
2021/11/08 14:51:18 got close notification. Produced: 65994, Consumed: 56417
``` 
 
p.s. thank you for the great work!

**Comment by brenol** [comment]
Makes sense - I noticed there were missing messages when I used the PublishConfirm example from the docs. 

Just reported because it took me sometime to notice my code was wrong and not all messages were being flushed. Wanted to do some graceful shutdown on my application.

Again, thank you for the great work! 🎈

**Comment by Gsantomaggio** [comment]
The `producer.send()` is asynchronous and stopping while publishing can raise this kind of problem.


A possible workaround  is to put an sleep before close so there is time to append and send all the pending messages:
```golang
time.Sleep(1 * time.Second)
if err := prod.Close(); err != nil {
    log.Println("could not close producer:", err)
}
```
I will investigate btw how to improve it.

**Comment by brenol** [comment]
Thanks! I ended up injecting env.Close though. Do you think it's better to sleep? (perhaps using `2 * producer.GetOptions().BatchPublishingDelay or something`).

**Comment by Gsantomaggio** [comment]
> Do you think it's better to sleep? (perhaps using 2 * producer.GetOptions().BatchPublishingDelay).

I mean it is ugly but it works :) 

This [fix](https://github.com/rabbitmq/rabbitmq-stream-go-client/pull/104/files#diff-d559b3105013c982547e4ece11f838aaf419f7760fb568191ffea5e8a0846e58R486-R488)  will help that basically it waits  for `BatchPublishingDelay`
