### ISSUE TITLE
createProducer going to the url go-stream-locator...?

### ISSUE THREAD

**Issue by stephenoneal** [rabbitmq/rabbitmq-stream-go-client#141]
On Darwin/ARM64:

This snippet of a larger file with ' CGO_ENABLED=1 GOOS=darwin GOARCH=arm64'

`
	// Connect to the broker ( or brokers )
	env, err := stream.NewEnvironment(
		stream.NewEnvironmentOptions().
			SetHost("127.0.0.1").
			SetPort(5552).
			SetUser("guest").
			SetPassword("guest"))
	CheckErr(err)
	fmt.Printf("------------------------------------------\n\n")
	fmt.Println("Connected to the RabbitMQ server")

	streamName := uuid.New().String()
	err = env.DeclareStream(streamName,
		&stream.StreamOptions{
			MaxLengthBytes: stream.ByteCapacity{}.GB(2),
		},
	)
	CheckErr(err)
	fmt.Printf("------------------------------------------\n\n")
	fmt.Printf("Created Stream: %s \n", streamName)

	producer, err := env.NewProducer(streamName, stream.NewProducerOptions().
		SetSubEntrySize(500).
		SetCompression(stream.Compression{}.None()))
	CheckErr(err)`

outputs:

` 
RabbitMQ Sub Entry Batch example
Success!------------------------------------------

Connected to the RabbitMQ server
Success!------------------------------------------

Created Stream: d5728a01-54e0-4cfb-8075-723fd84d7b9a 
dial tcp 23.45.205.250:5552: connect: connection refused %  
`

it appears that within environment.go, newReconnectClient does:

`
func (env *Environment) newReconnectClient() (*Client, error) {
	broker := env.options.ConnectionParameters[0]
	client := newClient("go-stream-locator", broker, env.options.TCPParameters)
`

and pinging 'go-stream-locator'...-
PING go-stream-locator (23.217.138.110): 56 data bytes
64 bytes from 23.217.138.110: icmp_seq=0 ttl=54 time=48.757 ms
64 bytes from 23.217.138.110: icmp_seq=1 ttl=54 time=21.787 ms
64 bytes from 23.217.138.110: icmp_seq=2 ttl=54 time=24.601 ms
64 bytes from 23.217.138.110: icmp_seq=3 ttl=54 time=23.961 ms
... ends up at an Akamai IP...

my expectation is that it would reconnect to the host originally configured in the environment.

**Comment by Gsantomaggio** [comment]
Hi @[stephenoneal](https://github.com/stephenoneal) 

The `locator-connection` lookups the `stream-metadata`.
The `stream-metadata` contains the node name where the stream is stored.
So the producer will use this information to connect to the node. 

It is not totally clear the problem to me. 
Can you please elaborate more? Thank you

**Comment by stephenoneal** [comment]
i'm getting an IP address that falls in Akamai subnet in the error message instead of 127.0.0.1

**Comment by stephenoneal** [comment]
I'm running rabbitmq-streams inside of a docker and running this golang locally-  so the Stream metadata on the stream itself could say that the hostname for the node is 'rabbitmq-hostname', but because I don't have that in local resolver I'll need to add it in /etc/hosts so they end up in the same location because even though the initial connect works (127.0.0.1) the followup is unusable (and in this case may conflict with something akamai has registered)?

**Comment by Gsantomaggio** [comment]
You need to set  the [advertised_host](https://www.rabbitmq.com/stream.html#advertised-host-port)

**Comment by Gsantomaggio** [comment]
using the config file or the environment variables like:
```
docker run -it --rm --name rabbitmq-stream \
		-p 5552:5552 -p 5672:5672 -p 15672:15672 \
		-e RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS="-rabbitmq_stream advertised_host localhost" \
		your_docker_image
```
