### ISSUE TITLE
Feature Request: Ability to Acknowledge Messages

### ISSUE THREAD

**Issue by EliHarper** [rabbitmq/rabbitmq-stream-go-client#147]
### Context:

I'd like to get some of the capabilities of streams in my application. What I'm looking for is a way to communicate with the next microservice in the series that has many replicas (running in k8s). 

### Problem:

The fan-out design of streams replicates messages since I haven't found a way to acknowledge each message sent (only one replica of each microservice should process a given message, all replicas share a queue). This paradigm seemed to work well with classic queues and auto-ack. 

### Desired Solution:

I believe if I can acknowledge messages using this client, as it [appears](https://stackoverflow.com/a/39054623) you're able to with Spring, I could ensure only one replica/consumer is processing each message in the stream. With this solution, I believe I'd be able to achieve better scalability (spawn more replicas to handle more messages when/if needed), and gain the durability of quorum queues with lower latency. 

If there's a way to get around the duplication of messages caused by the large fan-out, please let me know! Forgive me, I'm new to RabbitMQ, so I'm sure some of this may be a bit naive.

Thanks so much for any help you're able to provide.

**Comment by acogoluegnes** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(

**Comment by acogoluegnes** [comment]
There's no such thing as "acknowledgment" with streams. They model a append-only log, not a queue. "Offset tracking" is maybe what you're looking for though, as it allows a named consumer to restart where it left off. A [blog post](https://blog.rabbitmq.com/posts/2021/09/rabbitmq-streams-offset-tracking/) covers offset tracking, it uses the stream Java client for illustration, but offset tracking is a built-in feature of streams.

**Comment by Gsantomaggio** [comment]
See the [examples here ](https://github.com/rabbitmq/rabbitmq-stream-go-client/tree/main/examples):
- [Offset Tracking](https://github.com/rabbitmq/rabbitmq-stream-go-client/blob/main/examples/offsetTracking/offsetTracking.go)
- [Automatic Offset Tracking](https://github.com/rabbitmq/rabbitmq-stream-go-client/blob/main/examples/automaticOffsetTracking/automaticOffsetTracking.go)

**Comment by EliHarper** [comment]
Thank you both!!
