### ISSUE TITLE
Merge amqp091-go and Stream Client

### ISSUE THREAD

**Issue by percybolmer** [rabbitmq/rabbitmq-stream-go-client#203]
### Is your feature request related to a problem? Please describe.

Hello! I am a great fan of RabbitMQ and I have been using it rather much lately.

I would like to propose a rather big change, (woah my bad)

It is quite confusing right now, we have the https://github.com/rabbitmq/amqp091-go repository that you guys maintain that is frequently used.

Then we have this streaming Library which focuses on using RabbitMQ Streams, 

Now, to use rabbitMQ streams is really trivial, and having an extra repository for this makes it rather confusing as a user, and also not a very nice experience to now have 2 different imports. 

May I suggest, that the streaming Client is rather implemented into the AMQP Library that people are used to using?

I've been using AMQP lib for Streaming (it really only adds one or two headers to the amqp.Table to make it a stream)

I think that it would be less confusing for users if we have one library to refer to.

### Describe the solution you'd like

Merge any features that are needed from the Streaming Client into https://github.com/rabbitmq/amqp091-go. 

This also reduces overlapping/duplicate code. Right now we have one way to use TLS in amqp091 and another way here.

### Additional context

This is only a request to make a more uniformed solution for the Go community to use rabbitmq.

From my knowledge of streams It feels overkill having a whole separate lib for that purpose.

**Comment by Gsantomaggio** [comment]
>t is quite confusing right now, we have the https://github.com/rabbitmq/amqp091-go repository that you guys maintain that is frequently used.

> Then we have this streaming Library which focuses on using RabbitMQ Streams,

- Stream clients use the RabbitMQ stream Protocol (using the stream plugin)
- AMQP Clients use the AMQP091 protocol  (by default)
- Stream and AMQP Clients use two protocols and two TCP ports.
- You can use stream queues with AMQP clients and Stream clients. 

See here https://www.rabbitmq.com/stream-core-plugin-comparison.html for more details and to see the difference between stream core  and stream plugin 

A framework or library could include the two clients to abstract the behaviour, but it is out of scope for this client.

**Comment by percybolmer** [comment]
Thank you very much for clarifying this! Makes a lot of sense
