### ISSUE TITLE
Environment.QueryOffset hang/deadlock

### ISSUE THREAD

**Issue by HustonMmmavr** [rabbitmq/rabbitmq-stream-go-client#273]
### Describe the bug

Hello!
I met the scenario when call to the Environment.QueryOffset may hang: 

```go
package main

import (
	"fmt"
	"os"

	"github.com/rabbitmq/rabbitmq-stream-go-client/pkg/stream"
)

func CheckErr(err error) {
	if err != nil {
		fmt.Printf("%s ", err)
		os.Exit(1)
	}
}

func main() {
	env, err := stream.NewEnvironment(
		stream.NewEnvironmentOptions().
			SetHost("localhost").
			SetPort(5552).
			SetUser("guest").
			SetPassword("guest"))
	CheckErr(err)

	off, err := env.QueryOffset("consumer", "stream")
	fmt.Println(off, err)
}

```

Here is a description:
[`Environment.QueryOffset` calls](https://github.com/rabbitmq/rabbitmq-stream-go-client/tree/c390b3fa71525b1326d6931a9ecb1f27984b883e/pkg/stream/environment.go#L183) `Client.queryOffset` which internally:

1. [calls](https://github.com/rabbitmq/rabbitmq-stream-go-client/tree/c390b3fa71525b1326d6931a9ecb1f27984b883e/pkg/stream/client.go#L721)     [`Client.handleWriteWithResponse`](https://github.com/rabbitmq/rabbitmq-stream-go-client/tree/c390b3fa71525b1326d6931a9ecb1f27984b883e/pkg/stream/socket.go#L68-L83) with `removeResponse` argument passed as false (so RemoveResponseById won't be called and closing of response.data channel wouldn't be performed). The last function [calls `waitCodeWithDefaultTimeOut`](https://github.com/rabbitmq/rabbitmq-stream-go-client/tree/c390b3fa71525b1326d6931a9ecb1f27984b883e/pkg/stream/utils.go#L33-L50)
2. right after returning from the `handleWriteWithResponse` `queryOffset` starts accepting the offset value on the channel [here is a code on the next line](https://github.com/rabbitmq/rabbitmq-stream-go-client/tree/c390b3fa71525b1326d6931a9ecb1f27984b883e/pkg/stream/client.go#L722).

Thus there may occur a deadlock, when the response was finished by timeout (for example rabbit service unavailable), but the `Client.queryOffset` method still waiting the data on channel which wouldn't be closed. Seems that error check should be added before reading from channel, like it's done at [`Client.open`](https://github.com/rabbitmq/rabbitmq-stream-go-client/tree/c390b3fa71525b1326d6931a9ecb1f27984b883e/pkg/stream/client.go#L318-L327).
I suppose that next methods also may have a deadlock: [`Client.StreamStats`](https://github.com/rabbitmq/rabbitmq-stream-go-client/tree/c390b3fa71525b1326d6931a9ecb1f27984b883e/pkg/stream/client.go#L848-L853) and [`Client.queryPublisherSequence`](https://github.com/rabbitmq/rabbitmq-stream-go-client/tree/c390b3fa71525b1326d6931a9ecb1f27984b883e/pkg/stream/client.go#L607-L612)

### Reproduction steps

1. start rabbitmq server
2. setup breakpoint on this [line](https://github.com/rabbitmq/rabbitmq-stream-go-client/tree/c390b3fa71525b1326d6931a9ecb1f27984b883e/pkg/stream/client.go#L721)
3. run the code from the description and wait on the breakpoint
4. stop the rabbitmq server
5. continue code execution

### Expected behavior

No hang

**Comment by Gsantomaggio** [comment]
@HustonMmmavr  Thank you for the detailed report.

Feel free to propose a PR with the fix.
