### ISSUE TITLE
Exponential decrease in consumption performance as latency increases

### ISSUE THREAD

**Issue by hiimjako** [rabbitmq/rabbitmq-stream-go-client#293]
### Describe the bug

I was trying to do a benchmark to compare the performance in stream consumption of golang and java clients and I noticed a difference of about 3/4x in favor of java.
The most curious thing is that running this test even in a cloud environment, where latency is higher between client and server, the divergence increased dramatically.
It is obvious to expect a drop in performance with increasing latency, but it seems that in the case of the java client this decrease is about as linear as I would expect, while in the golang client this is much steeper bringing the performance difference between the clients to 15x in the case of 1ms latency and up to a 20x in the case of 5ms latency.

Some number about the benchmarks I've done could be found [here](https://github.com/hiimjako/compare-rabbitmq-stream-clients/tree/main/benchmark).

I was able to reproduce the problem locally as well, the instructions for doing so and the container setup is all [here](https://github.com/hiimjako/compare-rabbitmq-stream-clients).

### Reproduction steps

1. run a RabbitMQ server with streams enabled
2. create a stream and enter some data (around 15/20 million)
3. run the docker of `stream-perf-test` (java client) to consumer the stream from the beginning
4. run the docker of `go-stream-perf-test` (go client) to consumer the stream from the beginning

the difference in msg/s should be around 3/4x.

Repeat steps 3 and 4 by adding latency to the client containers (like 1/5ms), such as using the linux `tc` utility in a local environment or deploying them in a cloud environment.

the difference in msg/s should quickly increase to 10/15x or more.

### Expected behavior

I would expect to get about the same performance as the java client, or at least, not this dramatic drop in performance, since it seems possible as demonstrated by the java client.

### Additional context

I created a repository with all the above steps and the results I got in my machine, this should help to reproduce the issue quickly.
https://github.com/hiimjako/compare-rabbitmq-stream-clients
if anything else is needed I'm available

**Comment by Gsantomaggio** [comment]
Thank you, @hiimjako, for the detailed report and the repo.
I will have a look as soon as possible. 

In the meantime, can you please test the consumer without the docker/perftest, just using a regular consumer? 

I haven't updated the Golang perftest for a while since I was thinking of removing it in favour of the java-stream-perftest.

**Comment by hiimjako** [comment]
Yes sure! I'm on holiday until Monday, but as soon I will come back I will do it. However, I anticipate you that I don't think it will get different results, because this performance investigation started from a service I wrote with `ha.ReliableConsumer` which in an online cluster was consuming around 3750 msg/s, and I've obtained the same exact result running the docker/perftest and it was these results that made me wonder. (The docker/java one was running like 500k msg/s).

**Comment by Gsantomaggio** [comment]
Grazie. 
I'd need to investigate. I suppose the problem could be the channel between the socket and the user event-handler.
Enjoy your holiday! :)!

**Comment by hiimjako** [comment]
After some testing, I believe I've identified two issues:

1. Following your suggestion, I checked the AMQP 1.0 parser and was able to achieve a performance improvement of about 20% (by simply removing some unnecessary memory allocations). However, I suspect that there is still room for further optimization.
1. I believe I have identified the cause of the exponential drop in performance. The cause lies in the manual adjustment of the TCP socket ReadBuffer, specifically [this line](https://github.com/rabbitmq/rabbitmq-stream-go-client/blob/734d8e5e5724386243411241ae9781e078ef7299/pkg/stream/client.go#L169). Commenting out this line significantly speeds up the client, making it as fast as in the case of no latency. 

Now I think it's necessary to figure out how it could be fixed, one solution I would propose is that by default these tuning values be let the OS choose them automatically (so no call to `SetReadBuffer`), and call it only if the user wants to do fine-tuning to set them as they prefer, what do you think? Was there a reason for setting these parameters with the current default values?
Maybe the same logic can be applied even to `SetWriteBuffer`

**Comment by Gsantomaggio** [comment]
Thank you @hiimjako 

>Following your suggestion, I checked the AMQP 1.0 parser and was able to achieve a performance improvement of about 20% (by simply removing some unnecessary memory allocations). 

Fantastic ! 


> believe I have identified the cause of the exponential drop in performance. 
That's interesting. 

 >default these tuning values and let the OS choose them automatically
 
uhmm I like the idea, but we'd do some tests in different OS/scenarios like: VM/Docker/Linux/Windows 
but why not. 





I am doing some experiments on this branch https://github.com/rabbitmq/rabbitmq-stream-go-client/tree/performances_1 

Another small improvement is this:
https://github.com/rabbitmq/rabbitmq-stream-go-client/blob/40dab27b7a919a05deb6e4bdc9115b477fa43eaf/pkg/stream/server_frame.go#L428-L430

It is faster to read to buffer.

I am also trying to make the parse chunk parallel  ( two in this case ):

https://github.com/rabbitmq/rabbitmq-stream-go-client/blob/d6d82187050325f2128780c2fdca8a28b1c813b4/pkg/stream/deliver_queue.go#L20-L23

**Comment by hiimjako** [comment]
> uhmm I like the idea, but we'd do some tests in different OS/scenarios like: VM/Docker/Linux/Windows

Oh, yes, right. On Docker and Linux, this works. I have to test it on Windows and in a VM. I will let you know how the tests go.

> Another small improvement is this:

This was the same improvement I did :smile:
And on my machine did a lot of difference as I said 

> I am also trying to make the parse chunk parallel ( two in this case ):

This is interesting, I will take a look at the branch

**Comment by Gsantomaggio** [comment]
Parallel parse is just a test, and I am unsure about it.
The problem is to maintain the message order. This is why you see this:

https://github.com/rabbitmq/rabbitmq-stream-go-client/blob/d6d82187050325f2128780c2fdca8a28b1c813b4/pkg/stream/deliver_queue.go#L63-L65


Note: 
Focusing on performances without a precise scope can result in extreme optimization or refactoring that isn't useful in real applications.

So I'd like to avoid too much refactoring only to pass a test. I'll give you an example:  

Given a stream filled in this way:
```golang
for i := 0; i < 200_000_000; i++ {
   err = producer.Send(amqp.NewMessage([]byte(fmt.Sprintf("%d", I))))
   CheckErr(err)
   if i%500000 == 0 {
        fmt.Printf("Sent %d messages\n", I)
     }
}
```

Given the consumer in go:
```golang
	start := time.Now()
	startBeginning := time.Now()
	var recv int32
	handleMessages := func(consumerContext stream.ConsumerContext, message *amqp.Message) {

		id := fmt.Sprintf("%s", message.GetData())
		i, err := strconv.Atoi(id)
		if err != nil {
			fmt.Println(err)
		}
		if recv != int32(i) {
			fmt.Printf("Expected %d, got %d\n", recv, i)
		}
		if atomic.AddInt32(&recv, 1)%5000000 == 0 {
			fmt.Printf("[ %d  messages] - time elapsed: %s - from the begninning: %s\n", recv,
				time.Since(start), time.Since(startBeginning))
			start = time.Now()
		}

	}
```


and given the consumer in java:
```java
  environment.consumerBuilder().stream(stream)
                                        .offset(OffsetSpecification.first())
                                        .messageHandler(
                                                (context, message) -> {
                                                    String v = new String(message.getBodyAsBinary());
                                                    int vInt = Integer.parseInt(v);
                                                    if (vInt != recv.get()){
                                                        System.out.println("Expected " + recv + " but got " + vInt);
                                                    }
                                                    boolean b = recv.incrementAndGet() % 5000000 == 0;
                                                    if (b) {
                                                        Date date1 = new Date();
                                                        System.out.println("[" + recv + " messages] - time elapsed: " + (date1.getTime() - date.get().getTime()) + " - from the beginning: " + (date1.getTime() - dateStart.get().getTime()));
                                                        date.set(date1);
                                                    }
                                                })
                                        .build();
```


I have these results:
Golang:
```
[ 5000000  messages] - time elapsed: 1.6455105s - from the begninning: 1.645510417s
[ 10000000  messages] - time elapsed: 1.446954334s - from the begninning: 3.09247975s
[ 15000000  messages] - time elapsed: 1.456087334s - from the begninning: 4.5485795s
....
[ 185000000  messages] - time elapsed: 1.4408975s - from the begninning: 55.084682125s
[ 190000000  messages] - time elapsed: 1.461350042s - from the begninning: 56.546048667s
[ 195000000  messages] - time elapsed: 1.469939042s - from the begninning: 58.016005875s
[ 200000000  messages] - time elapsed: 1.501677417s - from the begninning: 59.517698709s
```


Java:
```
[5000000 messages] - time elapsed: 2107 - from the beginning: 2107
[10000000 messages] - time elapsed: 1861 - from the beginning: 3968
[15000000 messages] - time elapsed: 1893 - from the beginning: 5861
....
[180000000 messages] - time elapsed: 1600ms - from the beginning: 67239
[185000000 messages] - time elapsed: 1777ms - from the beginning: 69016
[190000000 messages] - time elapsed: 1746ms - from the beginning: 70762
[195000000 messages] - time elapsed: 1789ms - from the beginning: 72551
[200000000 messages] - time elapsed: 1773ms - from the beginning: 74324
```

So Go 59 seconds Java 74 seconds.

**Comment by hiimjako** [comment]
An update regarding the `SetReadBuffer` topic: I've discovered that setting the value `-1` in `stream.NewEnvironmentOptions.SetReadBuffer` is equivalent to not calling `connection.SetReadBuffer(c.tcpParameters.ReadBuffer)` underneath. This resolved the previously mentioned socket issue for me, and it made a significant difference in my case. I'm leaving this comment as documentation.

So for me the issue can be closed!

**Comment by Gsantomaggio** [comment]
Thank you @hiimjako ! I will do some test and will add some info to the documentation.
