### ISSUE TITLE
Filter support for Super Streams

### ISSUE THREAD

**Issue by jsearles** [rabbitmq/rabbitmq-stream-go-client#299]
### Is your feature request related to a problem? Please describe.

Filtering support looks to be implemented for streams, but this does not appear to be exposed for Super Streams.

### Describe the solution you'd like

Would like to be able to configure filtering to Super Stream, which would apply that filter to the individual streams.

**Comment by Gsantomaggio** [comment]
@jsearles thank you for reporting the issue
here is the PR https://github.com/rabbitmq/rabbitmq-stream-go-client/pull/300 
at the moment, it seems that there is a problem with https://codecov.io/ the PR pipeline is blocked in codecov.io upload

**Comment by Gsantomaggio** [comment]
Ok solved [here](https://github.com/rabbitmq/rabbitmq-stream-go-client/pull/300/commits/8fffe56bb51b4953e0a809b7b4b88d6671d65390)

**Comment by Gsantomaggio** [comment]
FIY: https://github.com/rabbitmq/rabbitmq-stream-go-client/releases/tag/v1.4.2
