### ISSUE TITLE
Ping rabbitmq / timeout

### ISSUE THREAD

**Issue by plaluisalves** [rabbitmq/rabbitmq-stream-go-client#312]
### Is your feature request related to a problem? Please describe.

Hi Guys, not sure if here is the right channel to ask, but is it possible to have a ping method for rabbitmq stream plugin or the timeout variable could be expose?
I m start and stop the container for rabbitmq, and if the container is down, I try to connect, at first, I received an error related with a timeout, and the second time is more fast.
The first error I got is this:
2024/06/07 14:12:30 [error] - timeout 10000 ns - waiting Code, operation: commandPeerProperties
2024/06/07 14:12:30 [error] - Can't set the peer-properties. Check if the stream server is running/reachable
The seconde error is this:
dial tcp 127.0.0.1:5552: connectex: No connection could be made because the target machine actively refused it.

### Describe the solution you'd like

 My question is, could this timeout be expose, and we define the timeout on EnvironmentOptions, I don't want to wait 10s just to find out that the server is down?

**Comment by Gsantomaggio** [comment]
Yes. It makes sense, but it will be for all the RPC calls. 
Will add something like:
```go
  .rpcTimeout(......)
```

**Comment by plaluisalves** [comment]
Thanks 😉

**Comment by Gsantomaggio** [comment]
@plaluisalves can you please try https://github.com/rabbitmq/rabbitmq-stream-go-client/pull/313?

**Comment by plaluisalves** [comment]
It is working! Thanks for the quick response and solution 😉

**Comment by Gsantomaggio** [comment]
FYI: https://github.com/rabbitmq/rabbitmq-stream-go-client/releases/tag/v1.4.5
