### ISSUE TITLE
lookup rabbitmq: no such host 

### ISSUE THREAD

**Issue by libracoder** [rabbitmq/rabbitmq-stream-go-client#315]
### Describe the bug

I am using this simple example to test the implementation of streams in my application , I have been testing this for days to no avail

```
func main() {
	env, err := stream.NewEnvironment(
		stream.NewEnvironmentOptions().
			SetHost("65.108.84.***").
			SetPort(5552).
			SetUser("root").
			SetPassword("***"))
	CheckErrSend(err)

	streamName := "hello"
	err = env.DeclareStream(streamName,
		&stream.StreamOptions{
			MaxLengthBytes: stream.ByteCapacity{}.GB(2),
		},
	)
	CheckErrSend(err)

	_, err = env.NewProducer(streamName, stream.NewProducerOptions())
	CheckErrSend(err)
```

I repeatedly get errors

`lookup rabbitmq: no such host`

The, I have enabled rabbitmq-streams using the plugin, The stream is also getting created.
This is the line that fails
`	_, err = env.NewProducer(streamName, stream.NewProducerOptions())
`

<img width="868" alt="image" src="https://github.com/rabbitmq/rabbitmq-stream-go-client/assets/32944039/da5310f3-d006-4e58-bc62-30b2651015cc">

### Reproduction steps

1. Create a main.go file
2. copy the code above and paste
3. Test
...

### Expected behavior

Throws the `lookup rabbitmq: no such host ` error

**Comment by Gsantomaggio** [comment]
Hi @libracoder 
If the node is behind a load-balancer/proxy/public IP you need to use the load-balancer configuration, see:
https://github.com/rabbitmq/rabbitmq-stream-go-client?tab=readme-ov-file#load-balancer

**Comment by Gsantomaggio** [comment]
@libracoder Can you try https://github.com/rabbitmq/rabbitmq-stream-go-client/pull/317 ?
