### ISSUE TITLE
v1.4.6 tagged as "v.1.4.6" - extra dot after v

### ISSUE THREAD

**Issue by jsearles** [rabbitmq/rabbitmq-stream-go-client#327]
### Describe the bug

This is causing issues with referencing this version by version#.

### Reproduction steps

❯ go get github.com/rabbitmq/rabbitmq-stream-go-client@v1.4.6
go: github.com/rabbitmq/rabbitmq-stream-go-client@1.4.6: invalid version: unknown revision 1.4.6

### Expected behavior

Version is successfully downloaded

### Additional context

N/A

**Comment by Gsantomaggio** [comment]
Ops ! Sorry! I need to automate the release process!

**Comment by Gsantomaggio** [comment]
It should be ok now! sorry !
