### ISSUE TITLE
Issue: Timeout Error When Running Super Stream Example on RabbitMQ 3.11

### ISSUE THREAD

**Issue by matheusrps** [rabbitmq/rabbitmq-stream-go-client#354]
### Describe the bug

Hi,

I've set up RabbitMQ with the following command:

`docker run -d --name rabbitmq -p 5552:5552 -p 15672:15672 -e RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS='-rabbitmq_stream advertised_host localhost -rabbit loopback_users "none"' rabbitmq:3.11.7-management`

Additionally, I enabled the stream management plugin:

`docker exec rabbitmq rabbitmq-plugins enable rabbitmq_stream_management`

I’m attempting to run the super stream producer example from the repository:

[examples/super_stream/producer/super_stream_producer.go](https://github.com/rabbitmq/rabbitmq-stream-go-client/blob/main/examples/super_stream/producer/super_stream_producer.go)

However, I keep encountering this error:

```
Super stream example - partitions
Connecting to RabbitMQ streaming ...
2024/09/25 10:08:27 [error] - timeout 10000 ns - waiting Code, operation: Command not handled 29, - invoices
timeout 10000 ms - waiting Code, operation: Command not handled 29, - invoices
```

Interestingly, the example works as expected when I upgrade RabbitMQ to version 3.13.

Am I missing any specific configuration for RabbitMQ 3.11, or is something else?

Thank you in advance for your help!

### Reproduction steps

1. run `docker run -d --name rabbitmq -p 5552:5552 -p 15672:15672 -e RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS='-rabbitmq_stream advertised_host localhost -rabbit loopback_users "none"' rabbitmq:3.11.7-management`
2. run `docker exec rabbitmq rabbitmq-plugins enable rabbitmq_stream_management`
3. go run [examples/super_stream/producer/super_stream_producer.go](https://github.com/rabbitmq/rabbitmq-stream-go-client/blob/main/examples/super_stream/producer/super_stream_producer.go)

### Expected behavior

I expected `invoices` superstream to be created.

**Comment by Gsantomaggio** [comment]
You need RabbitMQ 3.13.0 to create and delete the super-stream via client API

I added a check here: https://github.com/rabbitmq/rabbitmq-stream-go-client/pull/355

**Comment by Gsantomaggio** [comment]
- Before RabbitMQ 3.13.0, you need to use the command line tool to create a super stream.
- 3.11.x is an old version. I would suggest updating the server :)!
