### ISSUE TITLE
Change the stream creation

### ISSUE THREAD

**Issue by Gsantomaggio** [rabbitmq/rabbitmq-stream-go-client#99]
Make it idempotent as Java client does.

**Comment by victorges** [comment]
Oh, this is going to be great! I had to create some explicit logic for only creating the stream when it doesn't already exist which felt inconsistent with the other RabbitMQ experiences (like AMQP).

I wonder: when it already exists but we make a creation request with different configurations like changing the max length or message TTL, is the existing stream going to be reconfigured? Or are they "immutable" after creation?

**Comment by Gsantomaggio** [comment]
It will return an "precondition fail" error
